/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Spreadsheet;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author brian.marshall
 */
public class View extends javax.swing.JFrame {

    /**
     * Creates new form View
     */
    public View() {
        initComponents();
        this.setVisible(true);
        this.pack();
        this.setLocationRelativeTo(null);
        this.setSize(700, 460);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        clockInButton = new javax.swing.JButton();
        beginLunchButton = new javax.swing.JButton();
        endLunchButton = new javax.swing.JButton();
        clockOutButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        clockInButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Time Clock 1.gif"))); // NOI18N
        clockInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clockInButtonActionPerformed(evt);
            }
        });
        jPanel1.add(clockInButton);
        clockInButton.setBounds(50, 160, 120, 96);

        beginLunchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/clock out.jpg"))); // NOI18N
        beginLunchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beginLunchButtonActionPerformed(evt);
            }
        });
        jPanel1.add(beginLunchButton);
        beginLunchButton.setBounds(530, 160, 100, 100);

        endLunchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/lunchb.jpg"))); // NOI18N
        jPanel1.add(endLunchButton);
        endLunchButton.setBounds(200, 160, 130, 96);

        clockOutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/back-to-work.jpg"))); // NOI18N
        jPanel1.add(clockOutButton);
        clockOutButton.setBounds(360, 160, 129, 97);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/1-bg.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 700, 460);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clockInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clockInButtonActionPerformed
        try {
            Spreadsheet timeSheet = new Spreadsheet();
            timeSheet.clockIn();
        } catch (IOException ex) {
            Logger.getLogger(View.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_clockInButtonActionPerformed

    private void beginLunchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beginLunchButtonActionPerformed
        try {
            Spreadsheet timeSheet = new Spreadsheet();
            timeSheet.clockOut();
        } catch (IOException ex) {
            Logger.getLogger(View.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_beginLunchButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton beginLunchButton;
    private javax.swing.JButton clockInButton;
    private javax.swing.JButton clockOutButton;
    private javax.swing.JButton endLunchButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
